
theme: minima
plugins:
  - jekyll-relative-links
  - jekyll-katex
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - docs/V4_Gamma_Hook.markdown
katex:
  render_options:
    throw_on_error: false